export const ADD_PROFILE = 'ADD_PROFILE';
export const ADD_PROFILES = 'ADD_PROFILES';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_FAILED = 'PROFILE_FAILED';
export const ADD_SESSIONNAME = 'ADD_SESSIONNAME';
export const SESSIONNAME_LOADING = 'SESSIONNAME_LOADING';
export const SESSIONNAME_FAILED = 'SESSIONNAME_FAILED';